name: Build Linux Executable

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --release --bin manifest-store-cli

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: manifest-store
          path: target/release/manifest-store-cli
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/manifest-store-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
